# Generated by Django 3.2.8 on 2021-10-25 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20211025_1744'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myapp_card', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'CARD',
                'verbose_name_plural': 'CARD',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
