# Generated by Django 3.2.8 on 2021-10-25 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('myapp', '0002_servicecard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecard',
            options={'verbose_name': 'SERVICECARD', 'verbose_name_plural': 'SERVICECARD'},
        ),
        migrations.RenameField(
            model_name='servicecard',
            old_name='plantype',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='servicecard',
            name='data',
        ),
        migrations.RemoveField(
            model_name='servicecard',
            name='price',
        ),
        migrations.AddField(
            model_name='servicecard',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
