# Generated by Django 3.2.8 on 2021-10-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20211025_1744'),
        ('myapp', '0008_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page'),
        ),
    ]
